"""add uploader name to media model

Revision ID: 0703073e50b5
Revises: a7756d369c59
Create Date: 2025-04-22 23:28:45.423534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0703073e50b5'
down_revision = 'a7756d369c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medias', sa.Column('uploader', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medias', 'uploader')
    # ### end Alembic commands ###
