"""length is numeric not string 2

Revision ID: 0b574aef4b9d
Revises: cf1ba0d6b2a5
Create Date: 2020-05-27 13:55:11.284719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b574aef4b9d'
down_revision = 'cf1ba0d6b2a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('length', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'length')
    # ### end Alembic commands ###
