"""item add broadcast column for azura posting

Revision ID: 366ababdfa16
Revises: 91f800f15272
Create Date: 2020-06-10 14:27:27.039238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366ababdfa16'
down_revision = '91f800f15272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('broadcast', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'broadcast')
    # ### end Alembic commands ###
