"""Create Media relation for holding upload data

Revision ID: 36b6877016ce
Revises: 610e758af79c
Create Date: 2025-03-30 12:31:49.141338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36b6877016ce'
down_revision = '610e758af79c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medias',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('external_storage', sa.Boolean(), nullable=False),
    sa.Column('storage_process', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(), nullable=True),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medias')
    # ### end Alembic commands ###
