"""added language and frequency to shows

Revision ID: 3d0622f6021d
Revises: cb061821a625
Create Date: 2020-07-02 01:18:56.683096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3d0622f6021d"
down_revision = "cb061821a625"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shows", sa.Column("frequency", sa.Integer(), nullable=True))
    op.execute("UPDATE shows SET frequency = 1")
    op.alter_column("shows", "frequency", nullable=False)
    op.add_column("shows", sa.Column("language", sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shows", "language")
    op.drop_column("shows", "frequency")
    # ### end Alembic commands ###
