"""item remove unique constraint from episode number

Revision ID: 42f2db168fb2
Revises: 366ababdfa16
Create Date: 2020-06-10 14:30:34.980686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f2db168fb2'
down_revision = '366ababdfa16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('items_number_key', 'items', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('items_number_key', 'items', ['number'])
    # ### end Alembic commands ###
