"""add download count column to items

Revision ID: 42f604a9a641
Revises: 7d32bfecf3d8
Create Date: 2020-05-26 02:14:17.962928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f604a9a641'
down_revision = '7d32bfecf3d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('download_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'download_count')
    # ### end Alembic commands ###
