"""increase_max_size_of_social_base_url

Revision ID: 610e758af79c
Revises: ea81f5721b70
Create Date: 2023-06-14 09:53:04.998815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '610e758af79c'
down_revision = 'ea81f5721b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'social_base_url', existing_type=sa.String(length=108), type_=sa.String(length=256), existing_nullable=False)
    op.alter_column('shows', 'social_base_url', existing_type=sa.String(length=108), type_=sa.String(length=256), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'social_base_url', existing_type=sa.String(length=256), type_=sa.String(length=108), existing_nullable=False)
    op.alter_column('shows', 'social_base_url', existing_type=sa.String(length=256), type_=sa.String(length=108), existing_nullable=False)
    # ### end Alembic commands ###
