"""add column - fs_uniquifier to rel - users

Revision ID: 6fa7d5c511aa
Revises: 610e758af79c
Create Date: 2025-09-11 23:47:07.945474

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6fa7d5c511aa"
down_revision = "610e758af79c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("fs_uniquifier", sa.String(length=64), nullable=True)
        )
        batch_op.create_unique_constraint(None, ["fs_uniquifier"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("fs_uniquifier")

    # ### end Alembic commands ###
