"""added mandatory boolean active column w/ default to True && default frequency 1 / month

Revision ID: 76e6fb8087fa
Revises: 3d0622f6021d
Create Date: 2020-07-02 01:28:38.069410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "76e6fb8087fa"
down_revision = "3d0622f6021d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shows", sa.Column("active", sa.Boolean(), nullable=True))
    op.execute("UPDATE shows SET active = true")
    op.alter_column("shows", "active", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shows", "active")
    # ### end Alembic commands ###
