"""move live boolean from show to item

Revision ID: 91f800f15272
Revises: 0b574aef4b9d
Create Date: 2020-05-27 23:46:03.803193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91f800f15272'
down_revision = '0b574aef4b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('live', sa.Boolean(), nullable=True))
    op.drop_column('shows', 'live')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('live', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('items', 'live')
    # ### end Alembic commands ###
