"""Update Media relation with tie, binding

Revision ID: a7756d369c59
Revises: 36b6877016ce
Create Date: 2025-04-04 00:10:07.049241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7756d369c59'
down_revision = '36b6877016ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medias', sa.Column('binding', sa.String(), nullable=True))
    op.add_column('medias', sa.Column('tie', sa.String(), nullable=True))
    op.drop_column('medias', 'source_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medias', sa.Column('source_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('medias', 'tie')
    op.drop_column('medias', 'binding')
    # ### end Alembic commands ###
