"""alter week from int to array<int>

Revision ID: ad8ffcbd6dce
Revises: 7aca41a00507
Create Date: 2026-09-09 21:26:33.439510

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision = "ad8ffcbd6dce"
down_revision = "7aca41a00507"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shows", sa.Column("week_array", sa.ARRAY(sa.Integer)))
    shows = table(
        "shows", column("week", sa.Integer), column("week_array", sa.ARRAY(sa.Integer))
    )
    op.execute(
        shows.update()
        .where(shows.c.week == 1)
        .values({"week_array": op.inline_literal("{0, 1, 2, 3}")})
    )
    op.execute(
        shows.update()
        .where(shows.c.week == 0)
        .values({"week_array": op.inline_literal("{4}")})
    )
    op.drop_column("shows", "week")
    op.alter_column("shows", "week_array", nullable=False, new_column_name="week")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shows", sa.Column("week_temp", sa.Integer))
    shows = table(
        "shows", column("week", sa.ARRAY(sa.Integer)), column("week_temp", sa.Integer)
    )
    op.execute(
        shows.update()
        .where(shows.c.week == {0, 1, 2, 3})
        .values({"week_temp": op.inline_literal(1)})
    )
    op.execute(
        shows.update()
        .where(shows.c.week == {4})
        .values({"week_temp": op.inline_literal(0)})
    )
    op.drop_column("shows", "week")
    op.alter_column("shows", "week_temp", nullable=False, new_column_name="week")

    # ### end Alembic commands ###
