"""update item to new schema and add show table

Revision ID: b47b074673bb
Revises: e4390a710113
Create Date: 2020-05-26 01:04:27.086230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b47b074673bb'
down_revision = 'e4390a710113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('cover_image_url', sa.String(), nullable=True),
    sa.Column('playlist_name', sa.String(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('start', sa.Time(), nullable=False),
    sa.Column('end', sa.Time(), nullable=False),
    sa.Column('live', sa.Boolean(), nullable=True),
    sa.Column('archive_lahmastore', sa.Boolean(), nullable=True),
    sa.Column('archive_lahmastore_base_url', sa.String(), nullable=True),
    sa.Column('archive_mixcloud', sa.Boolean(), nullable=True),
    sa.Column('archive_mixcloud_base_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('playlist_name')
    )
    op.add_column('items', sa.Column('archive_lahmastore', sa.Boolean(), nullable=True))
    op.add_column('items', sa.Column('archive_lahmastore_canonical_url', sa.String(), nullable=True))
    op.add_column('items', sa.Column('archive_mixcloud', sa.Boolean(), nullable=True))
    op.add_column('items', sa.Column('archive_mixcloud_canonical_url', sa.String(), nullable=True))
    op.add_column('items', sa.Column('archived', sa.Boolean(), nullable=True))
    op.add_column('items', sa.Column('description', sa.String(), nullable=True))
    op.add_column('items', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('items', sa.Column('length', sa.String(), nullable=True))
    op.add_column('items', sa.Column('name', sa.String(), nullable=False))
    op.add_column('items', sa.Column('number', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('play_date', sa.Date(), nullable=False))
    op.add_column('items', sa.Column('play_file_name', sa.String(), nullable=True))
    op.add_column('items', sa.Column('uploaded_at', sa.DateTime(), nullable=False))
    op.add_column('items', sa.Column('uploader', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'items', ['number'])
    op.drop_column('items', 'show_name')
    op.drop_column('items', 'episode_cover_url')
    op.drop_column('items', 'episode_length')
    op.drop_column('items', 'episode_date')
    op.drop_column('items', 'source_url')
    op.drop_column('items', 'episode_number')
    op.drop_column('items', 'archive_url')
    op.drop_column('items', 'episode_title')
    op.drop_column('items', 'show_cover_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('show_cover_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('episode_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('archive_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('episode_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('source_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('episode_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('episode_length', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('episode_cover_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('show_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'items', type_='unique')
    op.drop_column('items', 'uploader')
    op.drop_column('items', 'uploaded_at')
    op.drop_column('items', 'play_file_name')
    op.drop_column('items', 'play_date')
    op.drop_column('items', 'number')
    op.drop_column('items', 'name')
    op.drop_column('items', 'length')
    op.drop_column('items', 'image_url')
    op.drop_column('items', 'description')
    op.drop_column('items', 'archived')
    op.drop_column('items', 'archive_mixcloud_canonical_url')
    op.drop_column('items', 'archive_mixcloud')
    op.drop_column('items', 'archive_lahmastore_canonical_url')
    op.drop_column('items', 'archive_lahmastore')
    op.drop_table('shows')
    # ### end Alembic commands ###
