"""length is numeric not string

Revision ID: cf1ba0d6b2a5
Revises: cbc935f15e11
Create Date: 2020-05-27 13:54:52.794035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf1ba0d6b2a5'
down_revision = 'cbc935f15e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'length')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('length', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
