"""Media secondaries with items, shows

Revision ID: df1201235a76
Revises: 0703073e50b5
Create Date: 2025-04-27 21:59:53.183726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df1201235a76'
down_revision = '0703073e50b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items_medias',
    sa.Column('media_id', postgresql.UUID(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['medias.id'], )
    )
    op.create_table('shows_medias',
    sa.Column('media_id', postgresql.UUID(), nullable=True),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['medias.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shows_medias')
    op.drop_table('items_medias')
    # ### end Alembic commands ###
