"""Remove key constraint for playlist name

Revision ID: f02d05e78a7a
Revises: 76e6fb8087fa
Create Date: 2021-10-04 15:56:14.206665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f02d05e78a7a'
down_revision = '76e6fb8087fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shows_playlist_name_key', 'shows', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('shows_playlist_name_key', 'shows', ['playlist_name'])
    # ### end Alembic commands ###
