"""empty message

Revision ID: ff6b0772ed42
Revises: 
Create Date: 2020-01-22 16:05:33.387189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ff6b0772ed42"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "items",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("show_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("show_cover_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("episode_number", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("episode_title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("episode_length", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "episode_cover_url", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column("episode_date", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("source_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("archive_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="items_pkey"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("items")
    # ### end Alembic commands ###
